SmartShop.Admin/Controllers/LoaiSanPhamController.cs
using SmartShop.DAL;
using SmartShop.Utilities.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartShop.Admin.Controllers
{
    public class LoaiSanPhamController : BaseController
    {
        //
        // GET: /LoaiSanPham/

        public ActionResult Index()
        {
            List<Category> data = new List<Category>();
            return View(data);
        }

        public JsonResult Delete(int id)
        {
            ProductCatSvr.Delete(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Save(Category model)
        {
            model.NoSymbolName = Util.converToUnsign(model.CategoryName);
            if (model.CategoryID == 0)
            {
                ProductCatSvr.Insert(model);
                return Json("", JsonRequestBehavior.AllowGet);
            }
            else
            {
                ProductCatSvr.Update(model);
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        public PartialViewResult GetData()
        {
            List<Category> data = ProductCatSvr.GetAllCategory();
            return PartialView(data);
        }

        public JsonResult GetDetail(int id)
        {
            Category data = new Category();
            if (id > 0)
                data = ProductCatSvr.GetById(id);
            string ret = RenderPartialHelper.RenderPartialToString(this.ControllerContext, Url.Content("~/Views/LoaiSanPham/GetDetail.cshtml"), data);
            return Json(ret, JsonRequestBehavior.AllowGet);
        }

    }
}

SmartShop.Admin/Views/LoaiSanPham/GetData.cshtml
@using SmartShop.DAL
@model List<Category>

@{
    foreach (var item in Model)
    {
    <tr>
        <td>@item.CategoryID</td>
        <td>@item.CategoryName</td>
        <td>@item.Description</td>
        <td>@item.NoSymbolName</td>
        <td>
            <a href="javascript:void(0);" onclick="createProcess('@item.CategoryID');">
                <i class="fa fa-lg fa-edit"></i>
            </a>
        </td>
        <td>
            <a href="javascript:void(0);" onclick="deleteProcess('@item.CategoryID');">
                <i class="fa fa-lg fa-trash-o"></i>
            </a>
        </td>
    </tr>
    }
}

SmartShop.Admin/Views/LoaiSanPham/GetDetail.cshtml
@using SmartShop.DAL
@model Category

<div id="insert-content">
    <div class="jarviswidget jarviswidget-sortable" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false" role="widget">
        <!-- widget div-->
        <div role="content">
            <!-- widget content -->
            <div class="widget-body no-padding">
                @using (Ajax.BeginForm("Save", "LoaiSanPham", null, new AjaxOptions() { HttpMethod = "POST", OnSuccess = "SaveSuccess" }, new { @class = "smart-form" }))
                {
                    <fieldset>
                        <div class="row">
                            <section class="col col-4">
                                <label class="label">Tên loại sản phẩm</label>
                            </section>
                            <section class="col col-8">
                                @Html.TextBox("CategoryID", @Model.CategoryID, new { @style = "display: none;" })
                                <label class="input">
                                    @Html.TextBox("CategoryName", @Model.CategoryName, new { @style = "width:100%; font-size:12px;" })
                                </label>
                            </section>
                        </div>
                        <div class="row">
                            <section class="col col-4">
                                <label class="label">Mô tả</label>
                            </section>
                            <section class="col col-8">
                                <label class="input">
                                    @Html.TextBox("Description", @Model.Description, new { @style = "width:100%; font-size:12px;" })
                                </label>
                            </section>
                        </div>
                        <label class="input">
                            <input type="submit" value="Thêm" id="LoaiSanPhamSubmit" style="display: none;" />
                        </label>
                    </fieldset>
                }

            </div>
            <!-- end widget content -->

        </div>
        <!-- end widget div -->

    </div>
</div>

SmartShop.Admin/Views/LoaiSanPham/Index.cshtml
@model List<SmartShop.DAL.Category>

@{
    ViewBag.Title = "Danh sách danh mục loại sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    function createProcess(id) {
        var obj = new Object();
        if (typeof id != "undefined")
            obj.id = id;
        else
            obj.id = 0;
        $.getJSON("/LoaiSanPham/GetDetail", obj, function (data) {
            var target = $("#dialog-insert");
            target.empty();
            target.append(data);
            target.attr("title", "Thông tin loại sản phẩm");
            $(".ui-dialog-title").html('Thông tin loại sản phẩm');
            DialogYesNoConfirm($("#dialog-insert"), 700, "Lưu", "Hủy", function () {
                var obj = new Object();
                obj.CategoryID = $('[name="CategoryID"]').val();
                obj.ParrentID = $('[name="ParrentID"]').val();
                obj.CategoryName = $('[name="CategoryName"]').val();
                obj.Description = $('[name="Description"]').val();
                obj.TRANG_THAI = $('[name="TRANG_THAI"]').val();

                if (obj.CategoryName == null || obj.CategoryName == "") {
                    $('[name="CategoryName"]').focus();
                    $('[name="CategoryName"]').select();
                    return;
                }
                else {
                    $('#LoaiSanPhamSubmit').click();
                    //$("#dialog-insert").dialog("close");
                }
            });
        });
    }

    function reloadProcess() {
        $("#tableBody").load("/LoaiSanPham/GetData");
    }

    function SaveSuccess(data) {
        alert('Lưu dữ liệu thành công.');
        $("#tableBody").load("/LoaiSanPham/GetData");
    }

    function deleteProcess(id) {
        if (id != "") {
            if (confirm('Bạn có chắc muốn xóa không ?')) {
                var obj = { id: id };
                $.getJSON("/LoaiSanPham/Delete", obj, function (data) {
                    $("#tableBody").load("/LoaiSanPham/GetData");
                });
            }
        }
    }
</script>

@Html.Partial("_ActionBar", null)

<div class="row">

    <!-- NEW WIDGET START -->
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-3" data-widget-editbutton="false">
            <header>
                <span class="widget-icon"><i class="fa fa-table"></i></span>
                <h2>Danh sách loại sản phẩm</h2>

            </header>

            <!-- widget div-->
            <div>

                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                    <!-- This area used as dropdown edit box -->

                </div>
                <!-- end widget edit box -->

                <!-- widget content -->
                <div class="widget-body no-padding">
                    <div class="widget-body-toolbar">
                    </div>
                    <table id="datatable_tabletools" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Tên danh mục loại</th>
                                <th>Mô tả</th>
                                <th>Rewrite Url</th>
                                <th>Sửa</th>
                                <th>Xóa</th>
                            </tr>
                        </thead>
                        <tbody id="tableBody">
                            @Html.Action("GetData")
                        </tbody>
                    </table>

                </div>
                <!-- end widget content -->

            </div>
            <!-- end widget div -->

        </div>
        <!-- end widget -->

    </article>
    <!-- WIDGET END -->
</div>
<div>
</div>
<div id="dialog-insert" style="display: none;">
    @Html.Partial("GetDetail", new SmartShop.DAL.Category())
</div>


<!-- PAGE RELATED PLUGIN(S) -->
<script src="@Url.Content("~/Scripts/js/plugin/datatables/jquery.dataTables-cust.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/ColReorder.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/FixedColumns.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/ColVis.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/ZeroClipboard.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/media/js/TableTools.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/DT_bootstrap.js")"></script>


<script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function () {

        pageSetUp();

        /*
         * BASIC
         */
        $('#dt_basic').dataTable({
            "sPaginationType": "bootstrap_full"
        });

        /* END BASIC */

        /* Add the events etc before DataTables hides a column */
        $("#datatable_fixed_column thead input").keyup(function () {
            oTable.fnFilter(this.value, oTable.oApi._fnVisibleToColumnIndex(oTable.fnSettings(), $("thead input").index(this)));
        });

        $("#datatable_fixed_column thead input").each(function (i) {
            this.initVal = this.value;
        });
        $("#datatable_fixed_column thead input").focus(function () {
            if (this.className == "search_init") {
                this.className = "";
                this.value = "";
            }
        });
        $("#datatable_fixed_column thead input").blur(function (i) {
            if (this.value == "") {
                this.className = "search_init";
                this.value = this.initVal;
            }
        });


        var oTable = $('#datatable_fixed_column').dataTable({
            "sDom": "<'dt-top-row'><'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
            //"sDom" : "t<'row dt-wrapper'<'col-sm-6'i><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'>>",
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "bSortCellsTop": true
        });



        /*
         * COL ORDER
         */
        $('#datatable_col_reorder').dataTable({
            "sPaginationType": "bootstrap",
            "sDom": "R<'dt-top-row'Clf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
            "fnInitComplete": function (oSettings, json) {
                $('.ColVis_Button').addClass('btn btn-default btn-sm').html('Columns <i class="icon-arrow-down"></i>');
            }
        });

        /* END COL ORDER */

        /* TABLE TOOLS */
        $('#datatable_tabletools').dataTable({
            "sDom": "<'dt-top-row'Tlf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
            "oTableTools": {
                "aButtons": ["copy", "print", {
                    "sExtends": "collection",
                    "sButtonText": 'Save <span class="caret" />',
                    "aButtons": ["csv", "xls", "pdf"]
                }],
                "sSwfPath": "@Url.Content("~/Scripts/js/plugin/datatables/media/swf/copy_csv_xls_pdf.swf")"
            },
            "fnInitComplete": function (oSettings, json) {
                $(this).closest('#dt_table_tools_wrapper').find('.DTTT.btn-group').addClass('table_tools_group').children('a.btn').each(function () {
                    $(this).addClass('btn-sm btn-default');
                });
            }
        });

        /* END TABLE TOOLS */
    })
</script>