SmartShop.Admin/Controllers/ThongTinChungController.cs
using SmartShop.Admin.Services;
using SmartShop.DAL;
using SmartShop.Utilities.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartShop.Admin.Controllers
{
    public class ThongTinChungController : BaseController
    {
        //
        // GET: /ThongTinChung/

        public ActionResult Index()
        {
            var data = ThongTinDAL.GetAllItem();//.Where(e => e.GroupInfo != "LOGO" && e.GroupInfo != "SLIDE");
            return View(data);
        }

        public JsonResult Delete(int id)
        {
            ThongTinChunSvr.Delete(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Save(HT_THONG_TIN model)
        {
            if (model.ID == 0)
            {
                ThongTinChunSvr.Insert(model);
                return Json("", JsonRequestBehavior.AllowGet);
            }
            else
            {
                ThongTinChunSvr.Update(model);
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }

        public PartialViewResult GetData()
        {
            List<HT_THONG_TIN> data = ThongTinChunSvr.GetAllItem().ToList();
            return PartialView(data);
        }

        public JsonResult GetDetail(int id)
        {
            HT_THONG_TIN data = new HT_THONG_TIN();
            if (id > 0)
                data = ThongTinChunSvr.GetById(id);
            string ret = RenderPartialHelper.RenderPartialToString(this.ControllerContext, Url.Content("~/Views/ThongTinChung/GetDetail.cshtml"), data);
            return Json(ret, JsonRequestBehavior.AllowGet);
        }

    }
}

SmartShop.Admin/Views/ThongTinChung/GetData.cshtml
@using SmartShop.DAL
@using SmartShop.Utilities
@model List<HT_THONG_TIN>

@{
    foreach (var item in Model)
    {
        string path = null;
        string check = null;
        if (item.GroupInfo.Equals("LOGO") || item.GroupInfo.Equals("SLIDE"))
        {
            path = HeThong.duongdan_anhPhysical(0, item.Value);
        }
        if (item.Available == 1)
        {
            check = "checked='checked'";
        }
        <tr>
            <td>@item.ID</td>
            <td>@item.GroupInfo</td>
            <td>@item.Info</td>
            <td>@item.Des</td>
            <td>@item.Value</td>
            <td style="text-align:center;">
                <label class="checkbox">
                    <input type="checkbox" name="checkbox-inline" @check>
                </label>
            </td>
            <td>
                @if (!path.IsNullOrEmpty())
                {
                    <img src="@path" width="60" height="60" alt="@item.Info">
                }
            </td>
            <td>
                <a href="javascript:void(0);" onclick="createProcess('@item.ID');">
                    <i class="fa fa-lg fa-edit"></i>
                </a>
            </td>
            <td>
                <a href="javascript:void(0);" onclick="deleteProcess('@item.ID');">
                    <i class="fa fa-lg fa-trash-o"></i>
                </a>
            </td>
        </tr>
    }
}

SmartShop.Admin/Views/ThongTinChung/GetDetail.cshtml
@using SmartShop.DAL
@model HT_THONG_TIN

<div id="insert-content">
    <div class="jarviswidget jarviswidget-sortable" id="wid-id-0" data-widget-editbutton="false" data-widget-custombutton="false" role="widget">
        <!-- widget div-->
        <div role="content">
            <!-- widget content -->
            <div class="widget-body no-padding">
                @using (Ajax.BeginForm("Save", "ThongTinChung", null, new AjaxOptions() { HttpMethod = "POST", OnSuccess = "SaveSuccess" }, new { @class = "smart-form" }))
                {
                    <fieldset>
                        <div class="row">
                            <section class="col col-4">
                                <label class="label">Nhóm</label>
                            </section>
                            <section class="col col-4">
                                @Html.TextBox("ID", @Model.ID, new { @style = "display: none;" })
                                <label class="input">
                                    @Html.TextBox("GroupInfo", @Model.GroupInfo, new { @style = "width:100%; font-size:12px;" })
                                </label>
                            </section>
                            <section class="col col-4">
                                @Html.CheckBox("Available", @Model.Available)
                                <i></i>Trạng thái
                                @*<label class="checkbox">
                                        <input type="checkbox" name="checkbox-inline" checked="checked">
                                    </label>*@
                            </section>
                        </div>
                        <div class="row">
                            <section class="col col-4">
                                <label class="label">Thông tin</label>
                            </section>
                            <section class="col col-8">
                                <label class="input">
                                    @Html.TextBox("Info", @Model.Info, new { @style = "width:100%; font-size:12px;" })
                                </label>
                            </section>
                        </div>
                        <div class="row">
                            <section class="col col-4">
                                <label class="label">Mô tả</label>
                            </section>
                            <section class="col col-8">
                                <label class="input">
                                    @Html.TextBox("Des", @Model.Des, new { @style = "width:100%; font-size:12px;" })
                                </label>
                            </section>
                        </div>
                        <div class="row">
                            <section class="col col-4">
                                <label class="label">Giá trị</label>
                            </section>
                            <section class="col col-8">
                                <label class="input">
                                    @Html.TextBox("Value", @Model.Value, new { @style = "width:100%; font-size:12px;" })
                                </label>
                            </section>
                        </div>
                        <div class="row">
                            <section class="col col-4">
                                <label class="label">Ảnh</label>
                            </section>
                            <section class="col col-8">
                                <div class="input input-file">
                                    <span class="button">
                                        <input type="file" id="fileAnhChinh" name="file" onchange="this.parentNode.nextSibling.value = this.value">Duyệt
                                    </span>
                                    <input name="Img" type="text" value="@Model.Value" placeholder="Include some files" readonly="">
                                </div>
                            </section>
                        </div>
                        <label class="input">
                            <input type="submit" value="Thêm" id="ThongTinChungSubmit" style="display: none;" />
                        </label>
                    </fieldset>
                }

            </div>
            <!-- end widget content -->

        </div>
        <!-- end widget div -->

    </div>
</div>

SmartShop.Admin/Views/ThongTinChung/Index.cshtml
@using SmartShop.DAL
@model List<HT_THONG_TIN>

@{
    ViewBag.Title = "Quản lý thông tin hiển thị";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    function createProcess(id) {
        var obj = new Object();
        if (typeof id != "undefined")
            obj.id = id;
        else
            obj.id = 0;
        $.getJSON("/ThongTinChung/GetDetail", obj, function (data) {
            var target = $("#dialog-insert");
            target.empty();
            target.append(data);
            target.attr("title", "Thông tin hiển thị");
            $(".ui-dialog-title").html('Thông tin hiển thị');
            DialogYesNoConfirm($("#dialog-insert"), 700, "Lưu", "Hủy", function () {
                var obj = new Object();
                obj.ProductGroupID = $('[name="ProductGroupID"]').val();
                obj.ParrentID = $('[name="ParrentID"]').val();
                obj.GroupName = $('[name="GroupName"]').val();
                obj.Description = $('[name="Description"]').val();
                obj.TRANG_THAI = $('[name="TRANG_THAI"]').val();

                if (obj.GroupName == null || obj.GroupName == "") {
                    $('[name="GroupName"]').focus();
                    $('[name="GroupName"]').select();
                    return;
                }
                else {
                    $('#ThongTinChungSubmit').click();
                    //$("#dialog-insert").dialog("close");
                }
            });
        });
    }

    function reloadProcess() {
        $("#tableBody").load("/ThongTinChung/GetData");
    }

    function SaveSuccess(data) {
        alert('Lưu dữ liệu thành công.');
        $("#tableBody").load("/ThongTinChung/GetData");
    }

    function deleteProcess(id) {
        if (id != "") {
            if (confirm('Bạn có chắc muốn xóa không ?')) {
                var obj = { id: id };
                $.getJSON("/ThongTinChung/Delete", obj, function (data) {
                    $("#tableBody").load("/ThongTinChung/GetData");
                });
            }
        }
    }
</script>

@Html.Partial("_ActionBar", null)

<div class="row">

    <!-- NEW WIDGET START -->
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-3" data-widget-editbutton="false">
            <header>
                <span class="widget-icon"><i class="fa fa-table"></i></span>
                <h2>Danh sách hiển thị</h2>

            </header>

            <!-- widget div-->
            <div>

                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                    <!-- This area used as dropdown edit box -->

                </div>
                <!-- end widget edit box -->
                <!-- widget content -->
                <div class="widget-body no-padding">
                    <div class="widget-body-toolbar">
                    </div>
                    <table id="datatable_tabletools" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nhóm</th>
                                <th>Thông tin</th>
                                <th>Mô tả</th>
                                <th>Giá trị</th>
                                <th>Trạng thái</th>
                                <th>Ảnh</th>
                                <th>Sửa</th>
                                <th>Xóa</th>
                            </tr>
                        </thead>
                        <tbody id="tableBody">
                            @Html.Action("GetData")
                        </tbody>
                    </table>

                </div>
                <!-- end widget content -->

            </div>
            <!-- end widget div -->

        </div>
        <!-- end widget -->

    </article>
    <!-- WIDGET END -->
</div>
<div>
</div>
<div id="dialog-insert" style="display: none;">
    @Html.Partial("GetDetail", new HT_THONG_TIN())
</div>


<!-- PAGE RELATED PLUGIN(S) -->
<script src="@Url.Content("~/Scripts/js/plugin/datatables/jquery.dataTables-cust.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/ColReorder.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/FixedColumns.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/ColVis.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/ZeroClipboard.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/media/js/TableTools.min.js")"></script>
<script src="@Url.Content("~/Scripts/js/plugin/datatables/DT_bootstrap.js")"></script>


<script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function () {

        pageSetUp();

        /*
         * BASIC
         */
        $('#dt_basic').dataTable({
            "sPaginationType": "bootstrap_full"
        });

        /* END BASIC */

        /* Add the events etc before DataTables hides a column */
        $("#datatable_fixed_column thead input").keyup(function () {
            oTable.fnFilter(this.value, oTable.oApi._fnVisibleToColumnIndex(oTable.fnSettings(), $("thead input").index(this)));
        });

        $("#datatable_fixed_column thead input").each(function (i) {
            this.initVal = this.value;
        });
        $("#datatable_fixed_column thead input").focus(function () {
            if (this.className == "search_init") {
                this.className = "";
                this.value = "";
            }
        });
        $("#datatable_fixed_column thead input").blur(function (i) {
            if (this.value == "") {
                this.className = "search_init";
                this.value = this.initVal;
            }
        });


        var oTable = $('#datatable_fixed_column').dataTable({
            "sDom": "<'dt-top-row'><'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
            //"sDom" : "t<'row dt-wrapper'<'col-sm-6'i><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'>>",
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "bSortCellsTop": true
        });



        /*
         * COL ORDER
         */
        $('#datatable_col_reorder').dataTable({
            "sPaginationType": "bootstrap",
            "sDom": "R<'dt-top-row'Clf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
            "fnInitComplete": function (oSettings, json) {
                $('.ColVis_Button').addClass('btn btn-default btn-sm').html('Columns <i class="icon-arrow-down"></i>');
            }
        });

        /* END COL ORDER */

        /* TABLE TOOLS */
        $('#datatable_tabletools').dataTable({
            "sDom": "<'dt-top-row'Tlf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
            "oTableTools": {
                "aButtons": ["copy", "print", {
                    "sExtends": "collection",
                    "sButtonText": 'Save <span class="caret" />',
                    "aButtons": ["csv", "xls", "pdf"]
                }],
                "sSwfPath": "@Url.Content("~/Scripts/js/plugin/datatables/media/swf/copy_csv_xls_pdf.swf")"
            },
            "fnInitComplete": function (oSettings, json) {
                $(this).closest('#dt_table_tools_wrapper').find('.DTTT.btn-group').addClass('table_tools_group').children('a.btn').each(function () {
                    $(this).addClass('btn-sm btn-default');
                });
            }
        });

        /* END TABLE TOOLS */
    })
</script>