SmartShop.UI/Controllers/GioHangController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using SmartShop.DAL;
using SmartShop.UI.Models;
using SmartShop.Utilities;
using SmartShop.UI.Service;

namespace SmartShop.UI.Controllers
{
    public class GioHangController : Controller
    {
        //
        // GET: /GioHang/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddToCart(string productId, int quantity = 0, string imgUrl = null, decimal price = 0)
        {
            var product = ProductSvr.GetByID(int.Parse(productId));
            var cartItem = new GioHangModel();
            if (product != null)
            {
                cartItem.ProductId = product.ProductID;
                cartItem.ProductCode = product.ProductCode;
                cartItem.ProductName = product.ProductName;
                cartItem.ImageUrl = imgUrl;
                cartItem.Quantity = quantity;
                cartItem.Price = price;
            }
            var items = new List<GioHangModel>();
            if (System.Web.HttpContext.Current.Session["ShoppingCart"].IsNullOrEmpty())
            {
                items.Add(cartItem);
                System.Web.HttpContext.Current.Session["ShoppingCart"] = items;
            }
            else
            {
                items = ((List<GioHangModel>)System.Web.HttpContext.Current.Session["ShoppingCart"]);
                var item = items.FirstOrDefault(x => x.ProductId == cartItem.ProductId && x.ProductCode == cartItem.ProductCode);
                if (!item.IsNullOrEmpty())
                    item.Quantity += quantity;
                else
                    items.Add(cartItem);
                System.Web.HttpContext.Current.Session["ShoppingCart"] = items;
            }

            UpdateShoppingCartCookie(items);

            return Json(new
            {
                Success = true,
                Message = "Thêm vào giỏ hàng thành công!"
            });
        }

        [HttpPost]
        public ActionResult RemoveFromCart(string productId)
        {
            var items = ((List<GioHangModel>)System.Web.HttpContext.Current.Session["ShoppingCart"]);

            if (items != null && items.Any())
            {
                var existItem = items.FirstOrDefault(x => x.ProductId == int.Parse(productId));
                if (existItem != null)
                {
                    items.Remove(existItem);
                }
            }
            if (items == null || !items.Any())
            {
                Session.Remove("ShoppingCart");
            }
            UpdateShoppingCartCookie(items);
            return Json(new
            {
                Success = true,
                Message = "Xóa khỏi giỏ hàng thành công!"
            });
        }

        public void UpdateShoppingCartCookie(List<GioHangModel> shoppingCart)
        {
            var cartItems = "";
            if (shoppingCart.Any())
            {
                cartItems = JsonConvert.SerializeObject(shoppingCart, Formatting.None);
            }
            var httpCookie = Response.Cookies["ShoppingCartCookie"];
            if (httpCookie != null)
                httpCookie.Value = cartItems;
        }

        [HttpPost]
        public ActionResult OrderNow(string trueName, string acountLogin, string acountPass, string email, string phone, string address)
        {
            var code = string.Empty;
            var member = new Member
            {
                TrueName = trueName,
                AcountLogin = acountLogin,
                AcountPass = acountPass,
                Email = email,
                Phone = phone,
                Address = address,
                MemberGroupID = (int)Constant.MemberGroupId.Customer,
                Acitve = true
            };

            var memberId = SysUserSvr.Insert(member);
            var items = ((List<GioHangModel>)System.Web.HttpContext.Current.Session["ShoppingCart"]);
            var total = items.Sum(t => t.Price);
            var order = new ShoppingOrder
            {
                MemberID = memberId,
                OrderDate = DateTime.Now,
                RequiredDate = DateTime.Now,
                ShipAddress = address,
                Status = 0,
                Total = (double)total
            };
            var orderDetails = items.Select(x => new ShoppingOrderDetail
            {
                ProductID = x.ProductId,
                Price = (int)x.Price,
                Amount = x.Quantity

            }).ToList();

            var status = ShoppingOrderSvr.Insert(order, orderDetails, ref code);
            if (status)
            {
                System.Web.HttpContext.Current.Session["ShoppingCart"] = null;
                if (Request.Cookies["ShoppingCartCookie"] != null)
                {
                    var myCookie = new HttpCookie("ShoppingCartCookie")
                    {
                        Expires = DateTime.Now.AddDays(-1d)
                    };
                    Response.Cookies.Add(myCookie);
                }
                return Json(new
                {
                    Success = true,
                    Message = "Đặt hàng thành công!"
                });
            }
            return Json(new
            {
                Success = true,
                Message = "Đặt hàng thất bại!"
            });
        }
    }
}

SmartShop.UI/Controllers/NhomsanphamController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartShop.DAL;
using SmartShop.Utilities;

namespace SmartShop.UI.Controllers
{
    public class NhomsanphamController : Controller
    {
        //
        // GET: /Nhomsanpham/

        public ActionResult Index(string groupId)
        {
            ProductGroup model = new ProductGroup();
            model = ProductGroupSvr.GetByID(groupId.StringToInt32());
            return View(model);
        }

    }
}

SmartShop.UI/Controllers/SanphamController.cs
using SmartShop.DAL;
using System;
using System.Data;
using System.Web.Mvc;
using SmartShop.Utilities;
using SmartShop.UI.Models;
using System.Collections.Generic;
using SmartShop.Utilities.Helper;

namespace SmartShop.UI.Controllers
{
    public class SanphamController : Controller
    {
        //
        // GET: /Sanpham/
        static int idSanPham = 0;
        static string pathAnhChinh = "";

        public ActionResult Index(int id)
        {
            ThongTinSanPhamModel data = new ThongTinSanPhamModel();
            if (id > 0)
            {
                Product obj = ProductSvr.GetByID(id);
                List<SP_SAN_PHAM_TTINH> lstThuocTinh = ProductSvr.getThuocTinhTheoSP(id);
                data.ProductID = obj.ProductID;
                data.ProductCode = obj.ProductCode;
                data.ProductName = obj.ProductName;
                data.NoSymbolName = obj.NoSymbolName;
                data.ProductSetID = obj.ProductSetID.Value;
                data.ProductGroupID = obj.ProductGroupID.Value;
                data.Quantity = obj.Quantity.Value;
                data.SizeID = obj.SizeID.Value;
                data.Viewed = obj.Viewed;
                data.Available = obj.Available.Value;

                foreach (SP_SAN_PHAM_TTINH item in lstThuocTinh)
                {
                    if (item.MA_TTINH.Equals("YTE_THUONG_HIEU"))
                        data.THUONG_HIEU = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_XUAT_XU"))
                        data.XUAT_XU = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_BAO_HANH"))
                        data.BAO_HANH = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_SO_TA"))
                        data.SO_TA = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_TINH_NANG"))
                        data.TINH_NANG = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_THONG_SO"))
                        data.THONG_SO = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_GIA_BAN"))
                        data.GIA_BAN = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("TAG"))
                        data.TAG = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_CHINH"))
                        data.ANH_CHINH = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_PHU_1"))
                        data.ANH_PHU_1 = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_PHU_2"))
                        data.ANH_PHU_2 = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_PHU_3"))
                        data.ANH_PHU_3 = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_PHU_4"))
                        data.ANH_PHU_4 = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_DANH_GIA"))
                        data.DANH_GIA = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_CHIET_KHAU"))
                        data.CHIET_KHAU = item.GIA_TRI;
                }
            }
            return View(data);
        }

        void layThongTin()
        {
            int totalRecord = 0;
            DataSet ds = ProductDAL.GetSanPhamTheoDieuKien(null, "", "ID", "GIAM", 10, 1, ref totalRecord, idSanPham);
            if (ds != null && ds.Tables.Count > 0)
            {
                DataTable dt = ds.Tables[0];
                if (dt != null && dt.Rows.Count > 0)
                {
                    image(dt.Rows[0]);
                    thongTinChung(dt.Rows[0]);
                    thongTinChiTiet(dt.Rows[0]);
                }
            }
        }
        
        public JsonResult GetDetail(int id)
        {
            ThongTinSanPhamModel data = new ThongTinSanPhamModel();
            if (id > 0)
            {
                Product obj = ProductSvr.GetByID(id);
                List<SP_SAN_PHAM_TTINH> lstThuocTinh = ProductSvr.getThuocTinhTheoSP(id);
                data.ProductID = obj.ProductID;
                data.ProductCode = obj.ProductCode;
                data.ProductName = obj.ProductName;
                data.NoSymbolName = obj.NoSymbolName;
                data.ProductSetID = obj.ProductSetID.Value;
                data.ProductGroupID = obj.ProductGroupID.Value;
                data.Quantity = obj.Quantity.Value;
                data.SizeID = obj.SizeID.Value;
                data.Viewed = obj.Viewed;
                data.Available = obj.Available.Value;

                foreach (SP_SAN_PHAM_TTINH item in lstThuocTinh)
                {
                    if (item.MA_TTINH.Equals("YTE_THUONG_HIEU"))
                        data.THUONG_HIEU = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_XUAT_XU"))
                        data.XUAT_XU = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_BAO_HANH"))
                        data.BAO_HANH = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_SO_TA"))
                        data.SO_TA = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_TINH_NANG"))
                        data.TINH_NANG = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_THONG_SO"))
                        data.THONG_SO = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_GIA_BAN"))
                        data.GIA_BAN = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("TAG"))
                        data.TAG = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_CHINH"))
                        data.ANH_CHINH = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_PHU_1"))
                        data.ANH_PHU_1 = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_PHU_2"))
                        data.ANH_PHU_2 = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_PHU_3"))
                        data.ANH_PHU_3 = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_ANH_PHU_4"))
                        data.ANH_PHU_4 = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_DANH_GIA"))
                        data.DANH_GIA = item.GIA_TRI;
                    else if (item.MA_TTINH.Equals("YTE_CHIET_KHAU"))
                        data.CHIET_KHAU = item.GIA_TRI;
                }
            }
            string ret = RenderPartialHelper.RenderPartialToString(this.ControllerContext, Url.Content("~/Views/SanPham/GetDetail.cshtml"), data);
            return Json(ret, JsonRequestBehavior.AllowGet);
        }

        void image(DataRow r)
        {
            pathAnhChinh = HeThong.duongdan_anhSP(Convert.ToInt32(r["ID"]), r["YTE_ANH_CHINH"].ToString());
            string pathAnhPhu1 = HeThong.duongdan_anhSP(Convert.ToInt32(r["ID"]), r["YTE_ANH_PHU_1"].ToString());
            string pathAnhPhu2 = HeThong.duongdan_anhSP(Convert.ToInt32(r["ID"]), r["YTE_ANH_PHU_2"].ToString());
            string pathAnhPhu3 = HeThong.duongdan_anhSP(Convert.ToInt32(r["ID"]), r["YTE_ANH_PHU_3"].ToString());
            string pathAnhPhu4 = HeThong.duongdan_anhSP(Convert.ToInt32(r["ID"]), r["YTE_ANH_PHU_4"].ToString());
            string strImg = "";
            strImg += "<div class=\"productdetail_image\">";
            strImg += "    <div id=\"left-chitiet\">";
            strImg += "        <div class=\"productdetai-wrapper\">";
            strImg += "            <div id=\"anh-to\">";
            strImg += "                <a class=\"anh-chinha highslide\" alt=\"\" rel=\"lightbox[roadtrip]\" href=\"javascript:ShowZoomDialog(true);\">";
            //strImg += "                    <span id=\"zoom\"></span>";
            strImg += "                <img class=\"anh-chinh cssimageproductone\" style=\"width:300px;\" alt=\"\" src=\"" + pathAnhChinh + "\">";
            strImg += "                </a>";
            strImg += "            </div>";
            strImg += "            <script>";
            strImg += "                $(window).load(function () {";
            strImg += "                    $(\".thumb_click\").click(function () {";
            strImg += "                        $('.anh-chinh').attr('src', $(this).attr('alt'));";
            //strImg += "                        $('.anh-chinha').attr('href', $(this).attr('alt'));";
            strImg += "                    });";
            strImg += "                });";
            strImg += "            </script>";
            strImg += "            <ul>";

            string strListImgZoom = "";
            //ltrZoomImg.Text = "<img id=\"ZoomImage\" src=\"" + pathAnhChinh + "\" height=\"440px\" style=\"width: auto\" onclick=\"\" />";
            strListImgZoom += "<div style=\"float: left; width: 85px; height: 85px; background: #FFF; margin-right: 2px; margin-top: 20px; margin-bottom: 10px;\">";
            strListImgZoom += "<a href=\"javascript:changeImage('" + pathAnhChinh + "');\"><img src=\"" + pathAnhChinh + "\" style=\"float: left; width: 85px; height: 85px\" />";
            strListImgZoom += "</div>";

            if (!pathAnhPhu1.Contains("no-image"))
            {
                strImg += "                <li class=\"active1\">";
                strImg += "                    <a href=\"" + pathAnhPhu1 + "\" rel=\"\"></a>";
                strImg += "                    <img id=\"anhconcon\" class=\"thumb_img thumb_click\" alt=\"" + pathAnhPhu1 + "\" src=\"" + pathAnhPhu1 + "\" style=\"width: 60px; height: 50px\">";
                strImg += "                </li>";

                strListImgZoom += "<div style=\"float: left; width: 85px; height: 85px; background: #FFF; margin-right: 2px\">";

SmartShop.UI/Views/Shared/_Categories.cshtml
@using SmartShop.UI
@{
    var cat = ProductCatSvr.GetAllCategory();
    var group = ProductGroupSvr.GetRootItem();
}
<div id="searchCate">
    <div class="parent-cate-title">
        <p>Danh mục sản phẩm</p>
        <ul class="parent-category">
            @foreach (var root in group)
            {
                <li>
                    @{
                        var url = Html.Raw(Url.Action("Index", "Nhomsanpham")) + "?groupId=" + root.ProductGroupID;
                    }
                    <a href="@url">@root.GroupName</a>
                    @{
                        var childOne = ProductGroupSvr.GetByParrent(root.ProductGroupID);
                    }
                    @if (childOne.Any())
                    {
                        <ul class="cate-child-one">
                            @foreach (var sub in childOne)
                            {
                                var subUrl = Html.Raw(Url.Action("Index", "Nhomsanpham")) + "?groupId=" + sub.ProductGroupID;
                                <li>
                                    <a href="@subUrl">
                                        @sub.GroupName
                                    </a>
                                    @{
                                        var childTwo = ProductGroupSvr.GetByParrent(sub.ProductGroupID);
                                    }
                                    @if (childTwo.Any())
                                    {
                                        <ul class="cate-child-two">
                                            @foreach (var sSub in childTwo)
                                            {
                                                var sSubUrl = Html.Raw(Url.Action("Index", "Nhomsanpham")) + "?groupId=" + sSub.ProductGroupID;
                                                <li>
                                                    <a href="@sSubUrl">@sSub.GroupName</a>
                                                </li>
                                            }
                                        </ul>
                                    }
                                </li>
                                        }
                        </ul>
                                        }
                </li>
                                        }
        </ul>
    </div>
</div>

SmartShop.UI/Views/Shared/_GroupHome.cshtml
@using SmartShop.UI
@using System.Data
@using SmartShop.DAL
@using SmartShop.Utilities
@{
    decimal giaBan = 0;
    decimal dChietKhau = 0;
    string chietkhau = "";
    var root = ProductGroupSvr.GetRootItem();
    int totalRecord = 0;
}
@foreach (var iroot in root)
{
    var lstGroup = ProductGroupSvr.GetByParrent(iroot.ProductGroupID);
    if (lstGroup.Count() > 0)
    {
        var url = Html.Raw(Url.Action("Index", "Nhomsanpham")) + "?groupId=" + iroot.ProductGroupID;
        DataSet mDs = ProductSvr.GetSanPhamTheoDieuKien(null, iroot.ProductGroupID.ToString(), null, null, 4, 1, ref totalRecord);
        if (mDs != null && mDs.Tables.Count > 0 && mDs.Tables[0].Rows.Count > 0)
        {
            <div class="giuacontent">
                <div class="indexblockwrp">
                    <div class="indexblockcontent">
                        <div id="dvrblhd" class="rightproblheader">
                            <div id="rprhdleft" class="rightproblheadertt">
                                <span id="ctl08_spTypeTT">
                                    <a href="@url">@iroot.GroupName</a>
                                </span>
                            </div>
                            <div id="dvxemnhanh" class="xemnhanhwrp">
                                <div id="drlist">
                                    <ul>
                                        <li class="drlist-sub">
                                            <span>&nbsp;</span>
                                            <ul>
                                                @foreach (var item in lstGroup)
                                                {
                                                    var subUrl = Html.Raw(Url.Action("Index", "Nhomsanpham")) + "?groupId=" + item.ProductGroupID;
                                                    string idNhom = item.ProductGroupID.ToString();
                                                    <li>
                                                        <a href="@subUrl">@item.GroupName</a>
                                                    </li>
                                                }

                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        @*<div class="indexblockheaderwrp">
                                <div class="indexblockcatname">
                                    <span>
                                        <a href="@url">@iroot.GroupName</a>
                                    </span>
                                </div>

                                <div class="indexblocksubcatwrp">
                                    <div class="indexblocksubcatcontent">

                                        @foreach (var item in lstGroup)
                                        {
                                            var subUrl = Html.Raw(Url.Action("Index", "Nhomsanpham")) + "?groupId=" + item.ProductGroupID;
                                            string idNhom = item.ProductGroupID.ToString();

                                            <div class="indexblocksubcatitem">
                                                <a href="@subUrl">@item.GroupName</a>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>*@
                        <div class="indexblockbodywrp">
                            @Html.Partial("_BestBuyInGroupHome", mDs)

                            <div class="indexblockbodycenterwrp2">
                                <div class="indexblbdcthd2">
                                    <div class="indexblbdcthdleft">
                                        &nbsp;
                                    </div>
                                    <div class="indexblbdcthdcenter2">
                                        <span>Sản Phẩm Thông Dụng</span>
                                    </div>
                                    <div class="indexblbdcthdright">
                                        &nbsp;
                                    </div>
                                </div>
                                <div class="indexblbdctprdwrp2">

                                    @foreach (var item in lstGroup)
                                    {
                                        string idNhom = item.ProductGroupID.ToString();
                                        DataSet ds = ProductSvr.GetSanPhamTheoDieuKien(null, idNhom, null, null, 8, 1, ref totalRecord);
                                        if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                                        {
                                            DataTable dt = ds.Tables[0];
                                            var showgroup = iroot.CategoryID + "dvNhom" + item.ProductGroupID.ToString();
                                            if (lstGroup.ToList().IndexOf(item) == 0)
                                            {

                                                foreach (DataRow r in dt.Rows)
                                                {
                                                    giaBan = decimal.Parse(r["YTE_GIA_BAN"].ToString());
                                                    dChietKhau = 0;
                                                    string path = HeThong.duongdan_anhSP(Convert.ToInt32(r["ID"]), r["YTE_ANH_CHINH"].ToString());
                                                    var href = Html.Raw(Url.Action("Index", "Sanpham")) + "?id=" + r["ID"];
                                                    if (r["YTE_CHIET_KHAU"] != null && !r["YTE_CHIET_KHAU"].ToString().Equals("") && decimal.Parse(r["YTE_CHIET_KHAU"].ToString()) > 0)
                                                    {
                                                        dChietKhau = decimal.Parse(r["YTE_CHIET_KHAU"].ToString());
                                                        chietkhau = String.Format("{0:0,0;(0:0,0);Liên hệ}", (dChietKhau / giaBan) * 100);
                                                    }

                                                    <div class="productitemwrp2">
                                                        <div class="productitemct">
                                                            <div class="productitemimgwrp">
                                                                <div class="productitemimgcontent">
                                                                    <a href="@href">
                                                                        <img src="@path" border="0" />
                                                                    </a>
                                                                </div>
                                                                <div class="noteevent">
                                                                    <span>New</span>
                                                                </div>
                                                            </div>
                                                            <div class="productitemcode">
                                                                <span>
                                                                    <a href="@href">@r["MA"].ToString()</a>
                                                                </span>
                                                            </div>
                                                            <div class="productitemdeskm">
                                                                <div class="productitemdes">
                                                                    <span>
                                                                        @r["TEN"].ToString()
                                                                    </span>
                                                                </div>
                                                                <div class="productitemkm">
                                                                    <span>
                                                                    </span>
                                                                </div>
                                                            </div>
                                                            <div class="productitemprice">
                                                                <span>
                                                                    @(String.Format("{0:0,0;(0:0,0);Liên hệ}", giaBan))
                                                                </span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                }
                                            }
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="indexblockadvbnwrp" style="display:none;">
                        <div class="indexblockadvct">
                        </div>
                    </div>
                    <div class="space10px" style="display:block;">
                        &nbsp;
                    </div>
                </div>
            </div>
        }
    }
}

SmartShop.UI/Views/Shared/_MenuLeft.cshtml
@using SmartShop.UI
@using SmartShop.Utilities
@model SmartShop.DAL.ProductGroup

@{
    var group = ProductGroupSvr.GetByParrent(Model.ProductGroupID);
    var parentUrl = Html.Raw(Url.Action("Index", "Nhomsanpham")) + "?groupId=" + Model.ProductGroupID;
    var groupName = Model.GroupName;
    if (!group.Any())
    {
        group = ProductGroupSvr.GetByParrent(Model.GroupParrentID.Value);
        parentUrl = Html.Raw(Url.Action("Index", "Nhomsanpham")) + "?groupId=" + Model.GroupParrentID;
        groupName = ProductGroupSvr.getParrent(Model.ProductGroupID).GroupName;
    }

}

<div id="dvleftblcathd" class="leftcolumblockhd">
    <span id="ctl08_spCatTitle">@groupName</span>
</div>
<div id="dvleftblct" class="leftcolumblockct">
    <div id="dvsubcat" class="leftsubcatwrp">
        @if (group.Any())
        {
            foreach (var item in group)
            {
                var url = Html.Raw(Url.Action("Index", "Nhomsanpham")) + "?groupId=" + item.ProductGroupID;
                <div id="dvsubcatitem" class="leftsubcatitem">
                    <a href="@url">@item.GroupName</a>
                </div>
            }
        }
    </div>
</div>

SmartShop.UI/Views/Shared/_ShoppingCart.cshtml
@using System.Data
@using SmartShop.UI
@using SmartShop.UI.Models
@using SmartShop.Utilities
@{
    var list = (List<GioHangModel>)HttpContext.Current.Session["ShoppingCart"];
}
<div class="top-cart-block">
    @if (list != null && list.Any())
    {
        <div class="top-cart-info">
            <a href="javascript:void(0);" class="top-cart-info-count">@list.Count sản phẩm</a>
            <span class="top-cart-info-value" id="topCartTotalValue">@String.Format("{0:0,0;(0:0,0);Liên hệ}", list.Sum(x => x.Price))</span>
        </div>
    }
    else
    {
        <div class="top-cart-info">
            <a href="javascript:void(0);" class="top-cart-info-count">0 sản phẩm</a>
        </div>
    }
    <i class="fa fa-shopping-cart"></i>

    <div class="top-cart-content-wrapper">
        <div class="top-cart-content">
            <ul class="scroller" style="height: 250px;">
                @{
                    if (list != null && list.Any())
                    {
                        foreach (var cart in list)
                        {
                            var href = Html.Raw(Url.Action("Index", "Sanpham")) + "?id=" + cart.ProductId;
                            <li>
                               <a href="@href"><img src="@cart.ImageUrl" alt="@cart.ProductName" width="37" height="34"></a>
                                <span class="cart-content-count">x @cart.Quantity</span>
                                <strong><a href="@href">@cart.ProductName</a></strong>
                                <em>@String.Format("{0:0,0;(0:0,0);Liên hệ}", cart.Price)</em>
                                <a href="javascript:void(0);" onclick="removeFromCart('@cart.ProductId')" class="del-goods">&nbsp;</a>
                            </li>
                        }
                    }
                    else
                    {
                        <li>
                            Không có sản phẩm nào trong giỏ hàng!
                        </li>
                    }

                }
            </ul>
            <div class="text-right">
                <a href="@Html.Raw(Url.Action("Index", "GioHang"))" class="btn btn-primary">Checkout</a>
            </div>
        </div>
    </div>
</div>